/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const DetailIndexLazyImport = createFileRoute('/detail/')()
const DetailDetailIdLazyImport = createFileRoute('/detail/$detailId')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DetailIndexLazyRoute = DetailIndexLazyImport.update({
  path: '/detail/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/detail/index.lazy').then((d) => d.Route))

const DetailDetailIdLazyRoute = DetailDetailIdLazyImport.update({
  path: '/detail/$detailId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/detail/$detailId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/detail/$detailId': {
      preLoaderRoute: typeof DetailDetailIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/detail/': {
      preLoaderRoute: typeof DetailIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  DetailDetailIdLazyRoute,
  DetailIndexLazyRoute,
])

/* prettier-ignore-end */
